#!/usr/bin/env php
<?php

/**
 * Mavision Console
 *
 * @package  Mavision
 * @author   Marwen Hlaoui <marwenhlaoui@gmail.com>
 */

/*
 * Start console time
 */
define('APP_START', microtime(true));

/*
 * Include composer auto loader
 */
require __DIR__.'/vendor/autoload.php';

